services:
  kafka:
    image: apache/kafka:4.1.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    restart: always

  auth:
    image: sloktulsyan/auth:latest
    container_name: auth
    env_file: ./services/auth/.env
    ports:
      - "5000:5000"
    depends_on:
      - kafka
    restart: always

  utils:
    image: sloktulsyan/utils:latest
    container_name: utils
    env_file: ./services/utils/.env
    ports:
      - "5001:5001"
    depends_on:
      - kafka
    restart: always

  user:
    image: sloktulsyan/user:latest
    container_name: user
    env_file: ./services/user/.env
    ports:
      - "5002:5002"
    depends_on:
      - kafka
    restart: always

  job:
    image: sloktulsyan/job:latest
    container_name: job
    env_file: ./services/job/.env
    ports:
      - "5003:5003"
    depends_on:
      - kafka
    restart: always

  client:
    image: sloktulsyan/client:latest
    container_name: client
    ports:
      - "3000:3000"
    restart: always